# 👥 04. Limpieza de Datos Demográficos (Clientes)

## 🎯 Objetivo de este Notebook
En este paso del pipeline (ETL), nos centraremos en el archivo de clientes (`customer-details.xlsx`). 
Aunque durante la fase de EDA observamos que este dataset estaba bastante limpio (sin nulos ni duplicados evidentes), es crucial estandarizar sus formatos (nombres de columnas, tipos de texto y fechas) para que coincidan exactamente con las reglas de negocio aplicadas al dataset del banco.

**Pasos a realizar:**
1. Carga de datos de clientes.
2. Estandarización de títulos y textos.
3. Casteo de fechas y revisión de tipos numéricos.
4. Exportación a la capa *Silver* (`customer_clean.csv`).

In [8]:
# -------------------------------------------------------------------------
# 1. CONFIGURACIÓN DEL ENTORNO Y CARGA DE DATOS
# -------------------------------------------------------------------------

# Recarga automática de módulos personalizados
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import os
import sys

# Configurar visualización de Pandas
pd.set_option('display.max_columns', None)

# Conectar con la ruta principal para importar nuestros scripts
sys.path.append(os.path.abspath(".."))
from src import sp_lim as sl

# Carga de datos originales y creación de la copia de trabajo
ruta_raw = "../data/customer-details.xlsx"
df_original = pd.read_excel(ruta_raw)
df_customer = df_original.copy()

print(f"✅ Entorno configurado. Datos cargados en memoria. Dimensiones: {df_customer.shape}")
display(df_customer.head(2))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
✅ Entorno configurado. Datos cargados en memoria. Dimensiones: (20115, 7)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097

## 🧹 Paso 1: Estandarización General
Utilizamos nuestras herramientas personalizadas para homogeneizar el formato del DataFrame. 
Pasaremos todos los títulos a formato `snake_case` y limpiaremos los valores de texto. Protegeremos las columnas identificadoras y de fecha (`id` y `dt_customer`) para no alterar su contenido crítico.

In [9]:
# -------------------------------------------------------------------------
# 2. ESTANDARIZACIÓN DE TÍTULOS Y TEXTOS
# -------------------------------------------------------------------------

# 1. Normalizar títulos (ej. 'NumWebVisitsMonth' -> 'numwebvisitsmonth', 'ID' -> 'id')
sl.limpiar_titulos(df_customer)

# 2. Normalizar textos
# Protegemos la columna 'id' (clave) y 'dt_customer' (fechas)
columnas_intocables = ['id', 'dt_customer'] 

sl.limpiar_texto(df_customer, columnas_a_ignorar=columnas_intocables)

print("✅ Estandarización completada. Vista previa (nota el formato snake_case):")
display(df_customer.head(3))

✅ Nombres de columnas estandarizados.
🧹 Limpiando contenido de 0 columnas...
✅ Textos estandarizados (sin ñ, espacios, puntos ni guiones).
✅ Estandarización completada. Vista previa (nota el formato snake_case):

,unnamed:_0,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b

## ⚙️ Paso 2: Correcciones Específicas
Para poder hacer un cruce relacional (Merge) más adelante con el dataset del banco, necesitamos que la clave primaria se llame exactamente igual. Cambiaremos `id` a `ID`. Además, parseamos la columna de alta del cliente al formato nativo de fechas de Pandas (`datetime64`).

In [10]:
# -------------------------------------------------------------------------
# 3. CORRECCIONES DE NEGOCIO Y TIPOS DE DATOS
# -------------------------------------------------------------------------

# 1. Renombrar clave primaria para homogeneizar con el dataset bancario
sl.cambiar_nombres(df_customer, {'id': 'ID'})

# 2. Casteo de fecha a formato estándar Pandas
df_customer['dt_customer'] = pd.to_datetime(df_customer['dt_customer'])

print("✅ Correcciones aplicadas. Tipos de datos actualizados:")
print(df_customer[['ID', 'dt_customer']].dtypes)
display(df_customer.head(3))

✅ Se han renombrado las columnas: ['id']
✅ Correcciones aplicadas. Tipos de datos actualizados:
ID                     object
dt_customer    datetime64[ns]
dtype: object

,unnamed:_0,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b

## 🛡️ Paso 3: Validación Numérica y Control de Calidad
Nos aseguramos de que la columna de ingresos (`income`) sea tratada como un valor numérico continuo. Por último, corremos nuestra función de control para garantizar que no existan filas idénticas duplicadas en nuestro dataset.

In [ ]:
# -------------------------------------------------------------------------
# 4. NÚMEROS Y CONTROL DE DUPLICADOS
# -------------------------------------------------------------------------

# 1. Asegurar formato numérico en la columna de ingresos ('income')
if 'income' in df_customer.columns:
    df_customer['income'] = pd.to_numeric(df_customer['income'], errors='coerce')

# 2. Control de calidad: Eliminación de filas duplicadas exactas
sl.eliminar_duplicados(df_customer)

print("\n--- INFO TÉCNICA (Verificación) ---")
df_customer.info()

✅ No se encontraron duplicados.

--- INFO TÉCNICA (Verificación) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   unnamed:_0         20115 non-null  int64
 1   income             20115 non-null  int64
 2   kidhome            20115 non-null  int64
 3   teenhome           20115 non-null  int64
 4   dt_customer        20115 non-null  datetime64[ns]
 5   numwebvisitsmonth  20115 non-null  int64
 6   ID                 20115 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 1.1+ MB

## 💾 Paso 4: Limpieza Final y Exportación
Eliminamos los residuos de la importación (como el índice que Excel a veces exporta como `unnamed:_0`) y guardamos el dataset consolidado en nuestra capa *Silver* (`procesados`).

In [12]:
# -------------------------------------------------------------------------
# 5. ELIMINACIÓN DE RESIDUOS Y GUARDADO INDIVIDUAL
# -------------------------------------------------------------------------

# 1. Borrar columnas residuales
sl.eliminar_columnas(df_customer, ['unnamed:_0'])

# 2. Guardado en la capa de procesados (Silver)
ruta_guardado = '../data/procesados/customer_clean.csv'
df_customer.to_csv(ruta_guardado, index=False)

print(f"🎉 ¡TRABAJO TERMINADO!")
print(f"💾 Archivo limpio guardado en: {ruta_guardado}\n")

# 3. Verificación final visual
print("--- 🔍 VISTA PREVIA DEL ARCHIVO FINAL ---")
display(df_customer.head(5))

🗑️ Columnas eliminadas: ['unnamed:_0']
🎉 ¡TRABAJO TERMINADO!
💾 Archivo limpio guardado en: ../data/procesados/customer_clean.csv

--- 🔍 VISTA PREVIA DEL ARCHIVO FINAL ---

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb